name: todo_flutter_app
description: Todo Task Management Flutter project.
publish_to: 'none' 
ersion: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_fonts: any
  parse_server_sdk_flutter: ^7.0.0
  cupertino_icons: ^1.0.2
  flutter_slidable: ^2.0.0
  awesome_snackbar_content: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  
  assets:
    - images/add_tasks.png

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
